name: monbil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.4
  lottie: ^3.3.1
  animated_splash_screen: ^1.3.0
  google_fonts: ^6.3.0
  path_provider: ^2.1.5
  flutter_animate: ^4.5.2
  qr_flutter: ^4.1.0
  flutterwave_standard: ^1.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - media/
    - assets/
